version: '3'
services:
  # web with xdebug - actency images
  web:
    # actency/docker-apache-php available tags: latest, 7.3., 7.2, 7.1-1.0, 7.1, 7.0, 5.6, 5.5, 5.4, 5.3, 8.0.1
    image: actency/docker-apache-php:5.4
    ports:
      - "80:80"
    environment:
      - SERVERNAME=agpb.local
      - SERVERALIAS=example2.local *.example2.local
      - DRUSH_VERSION=8
      - DOCUMENTROOT=agpb
    volumes:
      - /home/docker/projets/:/var/www/html/
      - /home/ubuntu/.ssh/:/var/www/.ssh/
      - ./config/php.ini:/usr/local/etc/php/php.ini
    links:
      - database:mysql
      - mailhog
    tty: true
    # Set logs driver to fluentd only if you enable the logs container
    # Add this logging section to any other container if you want the logs to be sent in es-fluentd-kibana container
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"

  # logs container - actency images
  logs:
    image: actency/docker-es-fluentd-kibana
    ports:
      - "8000:5601" # browse this port to see the logs in kibana
      - "9200:9200"
      - "9300:9300"
      - "24224:24224"

  # database container - actency images
  database:
    # actency/docker-mysql available tags: latest, 5.7, 5.6, 5.5
    image: actency/docker-mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=agpb
      - MYSQL_USER=eneovision
      - MYSQL_PASSWORD=eneo85
    volumes: 
      - "/var/www/mysql:/var/lib/mysql"
  # phpmyadmin container - actency images
  phpmyadmin:
    image: actency/docker-phpmyadmin
    ports:
      - "8010:80"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - UPLOAD_SIZE=1G
    links:
      - database:mysql

  # mailhog container - official images
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  # solr container - actency images
  solr:
    # actency/docker-solr available tags: latest, 6.2, 6.1, 6.0, 5.5, 5.4, 5.3, 5.2, 5.1, 5.0, 4.10, 3.6
    image: actency/docker-solr:6.2
    ports:
      - "8080:8983"

  # redis container - official images
#  redis:
#    image: redis:latest
#    ports:
#      - "6379"

  # phpRedisAdmin container - actency images
#  phpredisadmin:
#    image: actency/docker-phpredisadmin
#    ports:
#      - "9900:80"
#    environment:
#      - REDIS_1_HOST=redis
#    links:
#      - redis

  # Tika server container - actency images
#  tika:
#    image: actency/docker-tika-server
#    ports:
#      - "9998:9998"
